### ISSUE TITLE
Full Versionen von Bildern werden nicht indiziert

### ISSUE THREAD

**Issue by ReneHollander** [ReneHollander/rep0st#1]
Wenn ein Bild eine Full Version hat (full.pr0gramm.com), wird dieses nicht indiziert und kein Feature Vektor errechnet. Möchte man nun ein Bild testen, was nach dem Upload eine full Version erzeugen würde, wird dieses nicht gefunden.

**Comment by pr0nopoly** [comment]
Wenn es eine Full-Version gibt, ist der String bei der API-Antwort `"full" != null`. Du müsstest dann in der entsprechenden Zeile hier:
https://github.com/ReneHollander/rep0st/blob/master/rep0st/download.py#L116
Allerdings müsstest du da die `/items/info`-API verwenden, d.h. für jeden Post eine einzelne Abfrage. Hier würde ich eher bevorzugen, das CDN auszunutzen statt die API zu belasten.
Alternativ könntest du schauen, ob beim Bild von `img` die Breite 788px ist. Wenn ja, gibt es höchstwahrscheinlich ein `full`-Bild (und wenn nicht, dann halt weiter mit dem `img`-Bild arbeiten).

Oder du machst als erstes **immer** einen request auf `full`, schaust, ob da überhaupt was zurück kam und wenn nicht, arbeitest du mit `img`.

In der DB würde ich dann aber auch noch zusätzlich reinschreiben, ob es ein Full-Bild gibt.

**Comment by ReneHollander** [comment]
Ich werde mir das für den NodeJS Port aufheben.
Es wird wahrscheinlich schneller sein, zuerst einen Request auf full zu machen. Wenn ein 404 kommt auf img. Wahrscheinlich schneller, weil ich das JSON nicht parsen muss und ich einen 404 bekomme wenn es nix gibt und nicht erst der Server ein JSON File zusammenbasteln muss.

**Comment by ReneHollander** [comment]
Gefixed in https://github.com/ReneHollander/rep0st/commit/1dbaf5155d3525a9e35da6a558c704a531c41907
