### ISSUE TITLE
Fokus auf URL-TextBox setzten

### ISSUE THREAD

**Issue by AlexanderBottlang** [ReneHollander/rep0st#10]
Wenn die Seite lädt, wäre es schön, wenn der Fokus gleich auf die URL-TextBox gelegt wird.
Damit man nur rep0st öffnen muss und CTRL + V gefolgt von ENTER drücken muss um auf einen Repost zu prüfen.

**Comment by ReneHollander** [comment]
Ist ja schon lange gefixt...
