### ISSUE TITLE
Inkonsistenz zwischen Datenbank und Index

### ISSUE THREAD

**Issue by ReneHollander** [ReneHollander/rep0st#16]
Im Index können anscheinend Bilder enthalten sein, die es nicht in der Datenbank gibt. Eine Suche nach einem Bild das so einen Treffer in der Suche hat, führt zu einem 500 Server Error, da versucht wird ein Bild aus der Datenbank zu laden, dass es nicht gibt.

Beispiel: http://img.pr0gramm.com/2017/10/25/8fb1096c7fc677e4.jpg

**Comment by sm00thelf** [comment]
Kann man nicht die indizierten Bilder mit der Datenbank abgleichen um diese Inkonsistenz zu vermeiden?

**Comment by ReneHollander** [comment]
Der Index wird täglich neu mit den Daten in der Datenbank gebaut und eigentlich dürfte der oben beschriebene Fall nicht auftreten, da Posts im Normalbetrieb nicht aus der Datenbank gelöscht werden. Daher sollte einfach eine Überprüfung bei der Abfrage nach einem Post per ID gemacht werden. Sollte hier passieren: https://github.com/ReneHollander/rep0st/blob/master/rep0st/database.py#L196

**Comment by sm00thelf** [comment]
Wenn BIlder vom pr0gramm Server gelöscht werden, werden sie ja aus der Db gelöscht, kann es sein, dass das Problem da steckt?

**Comment by ReneHollander** [comment]
Ansich sollte das nur passieren, wenn alle Posts upgedated werden. Es wird alle 30 Sekunden abgefragt, ob Posts existieren die eine höhere ID aufweisen, als die höchste in der Datenbank. Diese Posts werden dann hinzugefügt, und erst nachdem dies geschehen ist, werden die Bilder heruntergeladen. Wenn dann kein Bild auf dem pr0gramm Server gefunden wird, weil es gelöscht wurde, wird es aus der Datenbank gelöscht. Und erst danach werden die Feature Vektoren generiert und in die Datenbank eingefügt. Also sollte das nicht vorkommen.
Werde die Tage mal versuchen die Ursache zu finden.

**Comment by ReneHollander** [comment]
Wurde irgendwann gefixt, glaube ich...
