### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by ReneHollander** [ReneHollander/rep0st#19]
Eine JSON API die es erlaubt Bilder (über Upload oder anhand URLs) oder Posts (per ID) zu analysieren wäre sinnvoll.

**Comment by FlorianMaak** [comment]
Eine seperate JSON-API muss nicht zwingend notwendig sein, sofern die URL analysiert/geparsed wird und dort ggf. die Post-ID extrahiert wird. Somit könnte man auch manuelle Suchen, die durch reguläre Seitenbesuche getriggert werden, mit dieser Logik versehen.

**Comment by sm00thelf** [comment]
rep0st.rene8888.at/api/search/ 
Da sitzt dann die API hinter oder?

**Comment by ReneHollander** [comment]
Anscheinend muss man den letzten `/` weglassen. Mit `https://rep0st.rene8888.at/api/search` funktioniert es. (Habe auch jetzt gerade erst deployed...)

**Comment by sm00thelf** [comment]
Benutzt die Seite jetzt auch schon die API?
Wenn ich mit POST nen Bild an die API schicke, sagt er mir, dass die Methode nicht auf der URL erlaubt wäre:
https://gyazo.com/653beb97763401c695331b04cb94bac6

Mein Fehler oder was auf der API Seite?

**Comment by ReneHollander** [comment]
Probier einmal zur Sicherheit mit https

**Comment by sm00thelf** [comment]
Jo, mit https gehts :)

**Comment by FlorianMaak** [comment]
Die API ist soweit schon nutzbar?
Dann würde ich mich an die Umsetzung des Frontends (#24) machen. 

**Des Weiteren hätte ich Vorschläge für die API:**
- 404er, wenn kein Bild gefunden wurde
- 406er, wenn das Bild/URL invalid ist (webm/gif/mp4)
- 400er Wenn der Payload fehlerhaft ist (Beibehalten)
- 200er, wenn Einträge gefunden wurden (Beibehalten)

Ergänzend würde ich über ein Ratelimit nachdenken (#20), sodass niemand auf die Idee kommt, jedes Bild auf dem pr0 durch dein Script zu jagen. Das schadet dem Board vermutlich nur. (Hier kannst du ja einen 429er zurückgeben)
Was sagst du dazu @ReneHollander ?

Edit: @sm00thelf Du kannst auf Github auch direkt Bilder hochladen. Somit sind sie auch immer vorhanden und nicht von einem externen Anbieter abhängig. D.h.: Die Bilder sind auch noch in 10 Jahren auf Github, wenn das Repo so lange hier liegt.

**Comment by sm00thelf** [comment]
![9275868925222f5b17ed601af47aa05f](https://user-images.githubusercontent.com/20225781/35164984-dcfe3200-fd4c-11e7-85d6-a8e97d3cb7c9.png)

**Comment by ReneHollander** [comment]
API geht soweit, muss noch die restlichen Endpoints einbauen.
Ähnliche Bilder findet er immer und ich kann schwer unterscheiden ob das Bild Invalid ist oder ein nicht unterstützter Datentyp ist. 404 wird dann eher bei einer URL oder Post ID auftreten.

Wenn jemand jedes Bild überprüfen möchte, muss er nur die Development VM verwenden, oder die pr0 eigene Repost Überprüfung verwenden, daher glaube ich nicht, dass ein Rate Limit vorerst so wichtig ist.

**Comment by sm00thelf** [comment]
pr0 hat ne eigene repost überprüfung?

**Comment by ReneHollander** [comment]
API ist soweit fertig: https://github.com/ReneHollander/rep0st/tree/master/docs/api
