### ISSUE TITLE
Rate Limiting und Statistiken

### ISSUE THREAD

**Issue by ReneHollander** [ReneHollander/rep0st#20]
Zumindest Statistiken sollten aufgezeichnet werden, da momentan nichts über die Auslastung oder Verwendung bekannt ist.

**Comment by FlorianMaak** [comment]
Aus gründen der Loyalität der Community über, sollte das Prüfen auf Rep0sts auf 1 Bild / 2sek begrenzt werden. 

In Kombination mit einem entsprechendem UserScript (bzw. Modifikationen dieses), sollte die Anzahl der möglichen Anfragen begrenzt werden, um eine Schädigung des Boards aufgrund von "sehr schnellen repost-markierungen" zu verhindern. UserScripts können ein Limit einführen, welches jedoch durch **manuelle Modifikationen** ausgehebelt werden könnte. Die Absicherung müssten also **leider serverside** umgesetzt werden.

**Alternativ** müsste eine **Prüfung aus dem UserScript entfernt** werden!

**Comment by ReneHollander** [comment]
Seite verwendet schon laenger Google Analytics und habe jetzt auch Prometheus support fuer ein paar einfache Dashboards.

Rate Limiting ist nachwievor nicht noetig.
