### ISSUE TITLE
Neues Design

### ISSUE THREAD

**Issue by ReneHollander** [ReneHollander/rep0st#24]
Diskussion zum neuen Design von rep0st.

**Comment by FlorianMaak** [comment]
Bezüglich des zusätzlichen Klicks, könnte man eine Checkbox auf der ersten Seite einbauen, welche den Status im LocalStorage ablegt. Dort liegt der dann auch schön lange.
![springen](https://user-images.githubusercontent.com/6325146/34686568-5251b634-f4ac-11e7-9f4a-efef0f2b4944.png)

**Comment by FlorianMaak** [comment]
> Damit könnte man zum Beispiel das Query Bild mit den Resultaten gegenüberstellen, was glaube ich ein nettes Feature wäre. Momentan ist es ja nicht möglich.

Das klingt nach einer sehr guten Idee.

Was genau möchtest du vergleichen? 
- Größere Ansichten der Bilder (Query und ausgewähltes Thumbnail)
- nur das Query-Bild in groß mit den Thumbnails
- beim :hover auf ein Thumb ein Tooltip mit Query- und Auswahl nebeneinander?

**Comment by sm00thelf** [comment]
Also ich kann mir die Variante 1 irgentwie am besten vorstellen, da man ja auf dem Thumbnails nichts sieht wenn die so klein sind, geht mir zumindest so.

Zu der letzten Variante: Meinst du das so, dass in dem Tooltip dann vergrößerte Ansichten angezeigt werden? Wenn ja wäre das auch eine schöne Variante.

**Comment by FlorianMaak** [comment]
> Meinst du das so, dass in dem Tooltip dann vergrößerte Ansichten angezeigt werden?

Genau so meine ich das, richtig.

**Comment by sm00thelf** [comment]
Dann würde ich vorschlagen dass man es wie folgt macht (ungefähr): Nach dem Klick auf Suche werden die Suchergebnisse in einem Raster oder in einer Liste aufgeführt (als Thumbnail). Mit einem Mausklick auf das Bild kommt man zum Post auf dem pr0gramm und wenn man nur mit dem Mauszeiger drüberfährt, bekommt man den Tooltip angezeigt. 
In den Tooltip kann man dann bestimmt auch noch neben das Ergebnisbild Daten einblenden wie Uploaddatum etc oder?

**Comment by FlorianMaak** [comment]
> In den Tooltip kann man dann bestimmt auch noch neben das Ergebnisbild Daten einblenden wie Uploaddatum etc oder?

Kann man theoretisch schon machen, ja. Mobil würde das Verhalten aber abweichen (müssen), da es dort kein :hover gibt.

**Comment by ReneHollander** [comment]
Ich hab mir sowas vorgestellt:
![vorschlag](https://user-images.githubusercontent.com/5379596/34877156-1f333b32-f7a5-11e7-827d-4ca23c91cbbd.jpg)
Bei Klick auf ein Bild öffnet sich das Bild größer, links und rechts sind dann die anderen. Dieser Modus kann auch geschlossen werden, damit man wieder auf die Übersicht aller Bilder kommt.
So sollte es auch unter Mobil gehen (wenn das Gerät im Hochformat ist, vielleicht untereinander statt nebeneinander).

**Comment by FlorianMaak** [comment]
Das wäre dann quasi die erste Variante, die ich vorgeschlagen habe.
Die sollte sich auch am produktivsten nutzen lassen, denke ich.

**Comment by ReneHollander** [comment]
Würde aber vorschlagen, dass dann als Single Page Application zu lösen. Ich werde mich einmal an #19 machen, damit man darauf aufbauen kann.

**Comment by sm00thelf** [comment]
So sieht das echt gut aus :D

**Comment by FlorianMaak** [comment]
Das war auch die Idee, das als Singlepage-App zu realisieren.
Fallbacks für Benutzer von NoScript oder anderen JS-Blockern werde ich dennoch mit einbauen. Da wäre es gut, wenn die POST-Variante bestehen bleibt natürlich. (Für JS-Nutzer greife ich dann auf die JSON-API zurück)

**Comment by ReneHollander** [comment]
Ich würde als Fallback vorerst einfach die alte Seite verwenden.

**Comment by FlorianMaak** [comment]
Kann man natürlich auch machen. So wie es dir lieber ist. 
Ich hätte das ganze sonst direkt so aufgebaut, dass die Seite beides kann.

**Comment by sm00thelf** [comment]
Wie sieht es eigentlich aus, bist du schon weitergekommen? @FlorianMaak

**Comment by FlorianMaak** [comment]
Habe aktuell recht viel um die Ohren. Ich markiere mir das mal, damit ich es nicht aus den Augen verliere.

**Edit:** Ich habe das mal in ein extra Repo ausgelagert, damit man das live verfolgen kann. Denke, dass ich morgen mal den Rest pushen werde. https://github.com/FlorianMaak/rep0st-frontend
Habe erstmal das grundlegende Markup, CSS (Auch mobil nutzbar) und JS umgesetzt.
Mobil und ohne JS ist das Ganze auch nutzbar. (Mediaqueries für Tablets fehlen aktuell jedoch noch)

Als nächstes folgen dann (in der Reihenfolge):
- webpack.config.js anlegen (Buildprozess mal vernünftig umsetzen. Habe das aktuell aus Faulheit mit PHPStorm gemacht)
- LESS aufräumen, logischer strukturieren und fehlende Mediaqueries hinzufügen
- Markup und CSS für den Upload
- Markup und CSS für die Ergebnisse (damit wäre die statische Version (ohne JS) schon lauffähig)
- JS für den Upload und Ausgabe
- Vergleichsansicht
- Anpassung an die Templateengine

**Comment by ReneHollander** [comment]
In https://github.com/ReneHollander/rep0st/commit/1dbaf5155d3525a9e35da6a558c704a531c41907 gab es ein kleines redesign. Ich finde weniger ist hier mehr, und bin sehr zufrieden das die Seite nun komplett ohne JavaScript auskommt (abgesehen von GA, tut aber nicht weh wenn das jemand blockiert).
