### ISSUE TITLE
DnD wie beim Upload von Bildern

### ISSUE THREAD

**Issue by pr0nopoly** [ReneHollander/rep0st#3]
Wäre geil, wenn man sowas hätte:

![Upload über Dran'n'Drop](https://i.imgur.com/nMjWa82.png)

**Comment by ReneHollander** [comment]
Wäre ein nettes Feature. Ich werde mich mal dran versuchen

**Comment by ReneHollander** [comment]
Ueber 60% der anfragen an rep0st kommen von Mobilgeraeten, daher finde ich dieses Feature zurzeit nicht noetig.
