### ISSUE TITLE
Change viewport to improve mobile accessibility

### ISSUE THREAD

**Issue by FloFaber** [ReneHollander/rep0st#31]
Buttons and checkboxes on mobile are very small.

The following code in the `<head>`-section would make it a lot better without breaking anything.
`<meta name="viewport" content="width=device-width, initial-scale=1"/>`

Before:
![x-mobile](https://user-images.githubusercontent.com/48768148/69994031-499e5600-154d-11ea-83e2-65feac80fe06.PNG)

After:
![x-desktop](https://user-images.githubusercontent.com/48768148/69994236-b44f9180-154d-11ea-83c5-9029a78dd400.PNG)

**Comment by ReneHollander** [comment]
Looks good, I will try it tomorrow and then merge.

Thanks!
