### ISSUE TITLE
internal server error API Error

### ISSUE THREAD

**Issue by 0xAdriian** [ReneHollander/rep0st#32]
Sobald ich den api/search?url= Endpoint aufrufe und ein Bild vor kurzer Zeit gepostet wurde auf dem pr0gramm kommt der fehler "internal server error" (Status 500) jedoch wenn ich normal auf der Website https://rep0st.rene8888.at/ diesen Request suche klappt es.

**Comment by ReneHollander** [comment]
Hast du vielleicht ein Beispiel Bild? Bist du dir sicher, dass der API request richtig ist und die URL im Query parameter richtig urlencoded ist?

**Comment by 0xAdriian** [comment]
Ein Beispielbild ist schwierig, da dieser Fehler nur bei Bildern auftritt die vor weniger als "<4 Stunden"? auf dem pr0 hochgeladen wurden.

**Comment by 0xAdriian** [comment]
^?
