### ISSUE TITLE
Falsche Bildreferenz für NSFW/NSFL Bilder

### ISSUE THREAD

**Issue by andrmoel** [ReneHollander/rep0st#37]
Bug nachstellen:
1. Nach einem beliebigen Bild suchen. z.B. https://img.pr0gramm.com/2021/04/09/8ecbeabefd095b69.jpg

Erwartetes Verhalten: Es werden alle Bilder angezeigt
Aktuelle Verhalten: Einige Bilder werden nicht angezeigt (vermutlich alle NSFW/NSFL)

Ich habe nun mal die Links untersucht. Nehmen wir das 3 Bild: https://pr0gramm.com/new/1248338 **(Achtung NSFW !!!)**
Der Repost Checker liefert hier eine falsche Bild URL aus.

Repost Checker gibt mir folgende Bild URL: https://img.pr0gramm.com/2016/03/30/e1d75fdd217eb504.jpg
Die korrekte URL im Beitrag ist jedoch: https://img.pr0gramm.com/2016/03/30/bdcc528dca95faab.jpg

Möglicherweise wurden die NSFW/NSFL Bilder im Pr0 auch neu indiziert, so dass sie einen neuen Hash bekommen haben.

**Comment by ReneHollander** [comment]
Nach dem Serverbrand haben sich anscheinend die URLs von einem grossteil der Bilder geandert. Ich arbeite daran dies zu fixen.

**Comment by ReneHollander** [comment]
Die URLs in der Datenbank wurden aktualisiert. Bug ist somit behoben.
