### ISSUE TITLE
Thumbnails in der Ergebnisliste

### ISSUE THREAD

**Issue by pr0nopoly** [ReneHollander/rep0st#6]
Vielleicht sollte man in der Ergebnisliste die Thumbnails statt der vollen Bilder verwenden, dann laden die Ergebnisse schneller.
Habe dazu mal nen PR gemacht:
https://github.com/ReneHollander/rep0st/pull/5

Kann aber u. U. auch besser sein, wenn man die vollen bilder anzeigt, da der Thumbnail ja nur einen Ausschnitt des Bildes zeigt. PR könnte man deshalb auch ablehnen. Ist Geschmackssache.

**Comment by ReneHollander** [comment]
Die Thumbnails zu verwenden wäre eine gute Idee, aber wie du schon angesprochen hast, sieht man dann nur einen Ausschnitt. Man könnte es wie im pr0 machen, wo dann die eigentlichen Bilder größer dargestellt werden, ist aber wie ich finde etwas Overkill...

**Comment by sm00thelf** [comment]
Kann geclosed werden oder?
