### ISSUE TITLE
GIF/WEBM-Support

### ISSUE THREAD

**Issue by pr0nopoly** [ReneHollander/rep0st#7]
Man muss die Frames der webms und gifs ja nicht einzeln vergleichen. Ein rudimentärer Vergleich reicht doch auch? Ist zumindest besser als nichts. Damit meine ich:
Folgende Eckdaten könnte man vergleichen:
- Thumbnail/erste Frame
- (Länge)
- (Framezahl)

**Comment by ReneHollander** [comment]
Schon etwas länger her, aber ich habe zur library node-phash erfolgreich die Berechnung des hashes für Videos hinzugefügt (nicht auf github). Die hashes werden aber mithilfe der hamming distance verglichen, wo ich keine schnelle Möglichkeit gefunden habe große Datenmengen zu verarbeiten
. ich werde das die Tage mal auf github packen und nochmal mit größeren datenmengen probieren.

Von Nexus 5 gesendet

**Comment by ReneHollander** [comment]
Duplicate of #34
