### ISSUE TITLE
Bookmarklet für die Rep0st-Suche

### ISSUE THREAD

**Issue by mYnDstrEAm** [ReneHollander/rep0st#9]
Mit einem Bookmarklet wäre eine schnelle Rep0st-Suche möglich was das Tool wirklich nützlich machen würde.
Das Bookmarklet muss dazu bloß als Lesezeichen hinzugefügt werden und in die Lesezeichen-Leiste gezogen werden. Wenn man dann irgendwo im Netz ein Bild findet braucht man bloß auf den Button klicken um zu schauen ob das schon mal gepostet wurde.

Ich denke dazu müsste man aber erst mal die Funktionalität für Issue #8 implementieren.

Hier ist Karmadecay's Bookmarklet:

javascript:(function(){url='//static.karmadecay.com/js/karma-decay-bookmarklet.js';document.body.appendChild(document.createElement('script')).src=url+'?'+new%20Date().getTime();})();

(http://static.karmadecay.com/js/karma-decay-bookmarklet.js)

Siehe: http://karmadecay.com/browser-tools

**Comment by ReneHollander** [comment]
Das sollte recht einfach umzusetzen sein. Werde zusammen mit #8 eine REST Schnittstelle zum Prüfen von Links einbauen.

**Comment by ReneHollander** [comment]
Mehr oder weniger gefixed. Bei dem Bookmarklet Code selber kenn ich mich nicht wirklich aus. Man kann nun aber via rep0st.rene8888.at/checkurl/<urlencoded_image_url> direkt einen Link überprüfen.
